# Site settings
baseurl = "https://aiprophets.com"
languageCode = "en-us"
title = "A.I. Prophets: The Minds Powering Artificial Intellegence"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-101997123-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "A.I. Prophets: The Minds Powering Artificial Intelligence"
    subtitle = "Learn about the Individuals Working Behind the Scenes of Machine Learning, Data Science, Quantum Computing & More"
    author = "ai_pr0phet" 
    description = "A.I. Prophet - An Ingishtful Grid Outlining the Minds Behind Artificial Intelligence"
    keywords = "AI, A.I., Artificial, Intelligence, Prophet, Prophets, grid, Quantum, Computer, Science, Data, Science, bookmarks, research, articles"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Learn More"

    # Footer text
    footertext = "Made by [ai_prophet](https://aiprophet.com/): -= ad majorem Dei gloriam =-"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
